### ISSUE TITLE
col sugestion

### ISSUE THREAD

**Issue by ysIgnacio** [voidfill/otherbot#7]
please make a port to kernel-mod plsplsplspllps i beg u

**Comment by ysIgnacio** [comment]
@voidfill @voidfill @voidfill @voidfill @voidfill @voidfill @voidfill @voidfill @voidfill @voidfill @voidfill @voidfill @voidfill @voidfill @voidfill @voidfill @voidfill @voidfill @voidfill @voidfill @voidfill @voidfill @voidfill @voidfill @voidfill @voidfill @voidfill @voidfill @voidfill @voidfill @voidfill @voidfill @voidfill @voidfill @voidfill @voidfill @voidfill @voidfill @voidfill @voidfill @voidfill @voidfill @voidfill @voidfill @voidfill @voidfill @voidfill @voidfill @voidfill @voidfill @voidfill @voidfill @voidfill @voidfill

**Comment by ysIgnacio** [comment]
reply >:(

**Comment by voidfill** [comment]
uh no

i dont wanna make selfbot plugins anymore

**Comment by ysIgnacio** [comment]
> uh no
> 
> i dont wanna make selfbot plugins anymore

sad
